# -*- coding: utf-8 -*-
"""Generate complete MerchantOS ADR set into /adrs. Documentation only."""
from pathlib import Path

ROOT = Path(r"C:\Users\Hadi\Desktop\projects\kasbino")
ADRS = ROOT / "adrs"
ADRS.mkdir(exist_ok=True)

# (num, slug, title, status, deps, context, problem, decision, why, alts, tradeoffs, tech, domain, analytics, security, impl, future, related_docs)
# deps: list of ints

RAW = []

def add(n, slug, title, status, deps, context, problem, decision, why, alts, tradeoffs, tech, domain, analytics, security, impl, future, related=""):
    RAW.append({
        "n": n, "slug": slug, "title": title, "status": status, "deps": deps,
        "context": context, "problem": problem, "decision": decision, "why": why,
        "alts": alts, "tradeoffs": tradeoffs, "tech": tech, "domain": domain,
        "analytics": analytics, "security": security, "impl": impl, "future": future,
        "related": related,
    })

# ---- PRODUCT & DOMAIN 001-015 ----
add(1, "product-architecture", "Product Architecture — Store-First Retention OS", "Accepted", [],
    "MerchantOS retains customers for local retail via POS identity capture, loyalty, storefront, and store PWA.",
    "Need a single product architecture aligning POS, membership, storefront, pickup, and analytics without becoming ERP/marketplace.",
    "Adopt store-first Customer Retention OS: each store owns POS, inventory, CRM/memberships, loyalty, storefront URL/QR/branding, installable store PWA; online fulfillment is pickup-only in MVP.",
    "Matches PRD core insight; maximizes merchant-owned relationships; avoids marketplace/delivery complexity.",
    "Marketplace model; delivery-first commerce; accounting-centric POS.",
    "Less horizontal marketplace GMV; sharper local retention focus.",
    "Guides all modules, ARDs 001–035, dual data planes PG+Mongo.",
    "StoreMembership, pickup Order, Store branding/geo become first-class.",
    "Instrument activation, QR, PWA, loyalty loops.",
    "Tenant isolation; no cross-merchant browsing.",
    "Implement per ADR roadmap; map to ARDs.",
    "Delivery/marketplace only via new ADRs.",
    "PRD.md; docs/product/store-first-evolution.md")

add(2, "ddd-strategy", "Domain-Driven Design Strategy", "Accepted", [1],
    "Complex retail domains (POS, loyalty, orders, analytics) must stay maintainable.",
    "Anemic CRUD or framework-centric models produce untestable business rules.",
    "Strict DDD: aggregates, VOs, domain events, repository interfaces in domain; application use cases; infra adapters.",
    "Enables extraction, testability, and ubiquitous language from PRD.",
    "Transaction script only; microservices-from-day-one.",
    "More upfront modeling than CRUD.",
    "Folder layout src/modules/<context>/{domain,application,infrastructure}.",
    "All bounded contexts follow domain-model.md.",
    "Domain events feed warehouse.",
    "Invariants in domain not UI.",
    "Enforce via rules/ddd-rules.md and reviews.",
    "CQRS/ES optional later.",
    "docs/architecture/14-ddd-architecture.md; domain-model.md")

add(3, "bounded-contexts", "Bounded Context Design", "Accepted", [2],
    "Multiple languages (sale vs order vs analytics) coexist.",
    "Shared god models couple storefront to POS internals.",
    "Contexts: Identity (merchant), Customer Identity, Merchant, Store, Catalog, Inventory, POS/Sales, CRM/Membership, Loyalty, Ordering(Pickup), Payments, Analytics(OLTP), Analytics(Platform/Mongo), Notifications, Admin, Realtime.",
    "Matches product seams and ARD packaging.",
    "Single shared kernel for everything.",
    "More integration events.",
    "Context map in 03-bounded-contexts.md; ACLs for storefront.",
    "Published language via events.",
    "Warehouse mirrors domain events.",
    "Admin separate role context.",
    "Implement module per context.",
    "Extract contexts per ADR on microservices.",
    "docs/architecture/03-bounded-contexts.md")

add(4, "modular-monolith", "Modular Monolith Strategy", "Accepted", [1, 2, 3],
    "Small team; MVP speed; extraction later.",
    "Premature microservices increase ops without product-market fit.",
    "Phase 1 modular monolith (Next.js); module boundaries + outbox for future extraction.",
    "Fast iteration + horizontal scale of stateless app.",
    "Microservices now; serverless-only.",
    "Deploy unit is whole app.",
    "Single deployable; workers share codebase.",
    "No cross-module DB joins in domain services.",
    "One outbox feeds many consumers.",
    "Shared security middleware.",
    "ARD-001 scaffolds modules.",
    "Extraction order in ADR-071+ / doc 20.",
    "docs/architecture/20-future-microservice-extraction.md")

add(5, "merchant-domain", "Merchant Domain", "Accepted", [3],
    "Merchants are tenants and paying customers.",
    "Need clear lifecycle draft→active→suspended.",
    "Merchant aggregate owns slug-adjacent identity of business; activation gates POS/storefront.",
    "Multi-tenant root.",
    "User=merchant conflation.",
    "Multi-store under merchant increases modeling.",
    "Tables merchants, settings; events Merchant*.",
    "AUTH-06 may create merchant on register.",
    "Activation funnel metrics.",
    "Admin suspend audited.",
    "ARD-003.",
    "Plans/billing later.",
    "ARD-003")

add(6, "store-domain", "Store Domain — Location Branding Slug", "Accepted", [5],
    "Store is operational and customer-facing unit.",
    "Missing geo/branding blocks pickup and store PWA.",
    "Store aggregate requires address+lat/lng, slug, branding, QR ref; one storefront surface per store.",
    "Enables pickup nav, QR, PWA manifests.",
    "Merchant-only slug without store.",
    "Mandatory geo may slow onboarding UX.",
    "stores table columns; MinIO logos.",
    "Store* events; StoreQrGenerated.",
    "StorefrontVisited attribution.",
    "Public location is intentional.",
    "ARD-004, 032, 033.",
    "Multi-location analytics later.",
    "store-location-architecture.md")

add(7, "customer-membership-domain", "Customer Membership Model", "Accepted", [3, 6],
    "Stores must own customer bases.",
    "Phone capture alone without membership blur ownership and loyalty scope.",
    "First-class StoreMembership (storeId,customerId,source); wallets scoped to membership; customer identity separate from merchant auth.",
    "Supports POS/QR/pickup join paths and portal.",
    "Global wallet across stores; shared CRM pool.",
    "Multi-membership UX complexity.",
    "store_memberships unique partial index.",
    "MembershipCreated events.",
    "Join funnel by source.",
    "Tenant filters on all member queries.",
    "ARD-031, 030, 008, 035.",
    "Cross-store loyalty programs Phase 2.",
    "customer-membership-architecture.md")

add(8, "catalog-inventory-domain", "Catalog and Inventory Domain", "Accepted", [6],
    "POS and storefront need products and stock.",
    "Coupling price and stock incorrectly causes oversell.",
    "Catalog owns Product; Inventory owns StockItem per store; barcode unique per merchant.",
    "POS hot path clarity.",
    "Single product-stock table blob.",
    "Two writes on sale.",
    "Indexes per indexing-strategy.",
    "InventoryChanged events.",
    "Low stock analytics.",
    "Audit stock adjusts.",
    "ARD-005, 006.",
    "Reservations for pickup.",
    "domain-model.md")

add(9, "pos-sales-domain", "POS and Sales Domain", "Accepted", [7, 8],
    "Retention starts at POS.",
    "Slow checkout kills adoption.",
    "Sale aggregate CompleteSale UoW: lines, membership upsert, stock, loyalty, receipt, outbox; <5s budget; phone required.",
    "Core North Star driver.",
    "Anonymous cash drawer only.",
    "Mandatory phone UX friction mitigated by keypad design.",
    "Idempotency-Key; Drizzle TX.",
    "SaleCompleted events.",
    "Checkout timings product analytics.",
    "Audit cancels.",
    "ARD-007.",
    "Offline sync ADR-024 staff PWA.",
    "PRD POS-*")

add(10, "loyalty-domain", "Loyalty Architecture", "Accepted", [7, 9],
    "Points drive returns.",
    "Informal discounts don't scale.",
    "Configurable PointRule; Wallet per membership; earn on sale and paid pickup; redeem at POS; customer-visible in portal.",
    "Closes loyalty growth loop.",
    "Third-party loyalty SaaS.",
    "Expiry policy defaults open (related proposed ADR).",
    "Ledger append-only.",
    "Points* events.",
    "FeatureUsed loyalty.",
    "Prevent negative balances.",
    "ARD-009, 035.",
    "Campaigns MVP+.",
    "growth-loops-loyalty.md")

add(11, "order-pickup-domain", "Pickup Order Architecture", "Accepted", [6, 7, 8],
    "Online demand without delivery ops.",
    "Delivery scope explodes MVP.",
    "Orders are pickup-only; statuses pending_payment→paid→preparing→ready_for_pickup→picked_up→completed|cancelled|refunded.",
    "Fits local retail foot traffic.",
    "Delivery; marketplace shipping.",
    "No courier revenue.",
    "Order status enum; no shipping tables.",
    "Pickup events replace OrderDelivered.",
    "Pickup funnel metrics.",
    "Refunds audited.",
    "ARD-011, 034, 012.",
    "Delivery requires new ADR.",
    "pickup-order-architecture.md")

add(12, "payment-domain", "Payment Domain", "Accepted", [11],
    "Pickup orders need digital payment path and fees.",
    "PSP for Iran undecided.",
    "PaymentGateway port + sandbox adapter; OrderPaid/Refunded; webhook verification; concrete PSP via future ADR.",
    "Unblocks architecture without vendor lock-in.",
    "Hardcode PSP now.",
    "Integration deferred risk.",
    "payments table; idempotency.",
    "OrderPaid warehouse.",
    "Payment failure analytics.",
    "Webhook signatures.",
    "ARD-012; docs/decisions ADR-0002.",
    "Choose PSP ADR-084.",
    "")

add(13, "admin-domain", "Admin Domain", "Accepted", [5],
    "Platform ops need control.",
    "Merchant APIs must not imply admin powers.",
    "Separate platform_admin role; merchant activate/suspend; security monitoring hooks.",
    "Protects multi-tenant SaaS.",
    "All merchants are admins.",
    "Extra UI surface.",
    "admin routes; audit every action.",
    "AdminAction events.",
    "Mgmt dashboards ARD-025.",
    "Strict RBAC.",
    "ARD-018, 026.",
    "Growth tooling Phase 2.",
    "")

add(14, "analytics-domain-boundaries", "Analytics Domain Boundaries OLTP vs Mongo", "Accepted", [1, 3],
    "Need merchant KPIs and product/platform telemetry.",
    "Putting clickstream in Postgres endangers POS.",
    "OLTP merchant dashboards (AN-*) on PostgreSQL projections; product/audit/warehouse/clickstream on MongoDB.",
    "Protects latency; flexible telemetry.",
    "Single store for all analytics.",
    "Two query stacks.",
    "ARD-016 vs 021–028.",
    "Money truth stays PG.",
    "Dual-read discipline.",
    "Admin-only platform analytics.",
    "analytics-architecture.md.",
    "Warehouse→warehouse BI later.",
    "ADR-056+")

add(15, "scope-guardrails", "MVP Scope Guardrails and Non-Goals", "Accepted", [1],
    "Scope creep into ERP/delivery kills MVP.",
    "AI agents may invent features.",
    "Hard non-goals: delivery/courier/shipping, marketplace browsing, full accounting, supplier networks, desktop offline suite.",
    "Keeps ARD/ADR executable.",
    "Build everything now.",
    "Deferred revenue streams.",
    "Skill prohibitions encode this.",
    "No delivery aggregates.",
    "No delivery funnels.",
    "Less attack surface.",
    "Reject PRs/ADRs violating non-goals without superseding ADR.",
    "Supersede via new ADR only.",
    "PRD §3")

# ---- FRONTEND 016-028 ----
add(16, "nextjs-architecture", "Next.js Application Architecture", "Accepted", [4],
    "Need unified TS full-stack.",
    "Separate Nest+React doubles work.",
    "Next.js 15+ App Router hosts UI, Route Handlers, Server Actions in modular monolith.",
    "One repo velocity; RSC for dashboards.",
    "Remix; separate API gateway only.",
    "Couple deploy of UI+API.",
    "app/ routes compose modules.",
    "Presentation layer only calls application.",
    "correlationId middleware.",
    "Secure cookies.",
    "ARD-001.",
    "Edge later.",
    "docs/tech/nextjs.md")

add(17, "app-router-structure", "App Router Structure", "Accepted", [16],
    "Multiple audiences: merchant, customer, admin, marketing.",
    "Flat routes confuse auth.",
    "Route groups: (marketing), (merchant), (storefront)/s/[slug], (admin), api/v1.",
    "Clear auth boundaries.",
    "Single group for all.",
    "More folders.",
    "Middleware coarse gates.",
    "N/A",
    "PageViewed by path.",
    "Separate cookie paths if needed.",
    "Scaffold in ARD-001/010/018/029.",
    "i18n routes later.",
    "")

add(18, "component-architecture", "Frontend Component Architecture", "Accepted", [16, 19],
    "Need consistent UI ownership.",
    "God components with DB access.",
    "shared/ui primitives; module ui compositions; no domain imports in client components.",
    "DDD-friendly UI.",
    "Feature-sliced only without modules.",
    "Discipline required.",
    "Matches uiux component-library.",
    "N/A",
    "FeatureUsed on key CTAs.",
    "No secrets in client bundles.",
    "uiuxpromax before new UI.",
    "Storybook optional.",
    "docs/uiux/component-library.md")

add(19, "shadcn-ui", "shadcn/ui Strategy", "Accepted", [18],
    "Need accessible components owned in repo.",
    "Heavy design systems slow MVP.",
    "shadcn/ui + Radix copied into src/shared/ui; customize via tokens.",
    "A11y + ownership.",
    "MUI; Chakra; custom from scratch.",
    "Must keep upstream merges manual.",
    "CLI generate components.",
    "N/A",
    "N/A",
    "Keep focus management.",
    "ARD UI work.",
    "Design system evolution ADR.",
    "docs/tech/shadcn-ui.md")

add(20, "tailwind-design-system", "Tailwind Design System Strategy", "Accepted", [19],
    "Need mobile-first styling.",
    "Ad-hoc CSS thrash.",
    "Tailwind with CSS variables/tokens; mobile-first; avoid banned AI aesthetic defaults per design rules.",
    "Speed + consistency.",
    "CSS modules only.",
    "Utility verbosity.",
    "globals.css tokens.",
    "N/A",
    "N/A",
    "Contrast AA.",
    "docs/uiux/design-system.md.",
    "RTL polish later.",
    "docs/tech/tailwindcss.md")

add(21, "uiuxpromax-governance", "uiuxpromax Mandatory for UI", "Accepted", [18, 20],
    "AI UI quality variance.",
    "Inconsistent UX breaks POS speed and brand.",
    "Every UI task invokes uiuxpromax before code; failure = not Done.",
    "Enforces design system.",
    "Freeform AI UI.",
    "Dependency on skill availability.",
    "Skill gate in ard-to-code.",
    "N/A",
    "N/A",
    "A11y from design-rules.",
    "Stop if skill missing.",
    "Replace only via ADR.",
    "docs/skills/uiuxpromax-integration.md")

add(22, "merchant-staff-pwa", "Merchant Staff PWA Architecture", "Accepted", [16, 24],
    "Staff need installable POS.",
    "Conflating with store PWA confuses users.",
    "Separate staff PWA for POS/offline queue (ARD-017); MerchantOS branding.",
    "Peak-hour reliability.",
    "One PWA for everyone.",
    "Two manifests to maintain.",
    "SW + IDB sale queue.",
    "N/A",
    "AppOpened source=staff-pwa.",
    "httpOnly cookies; isolate from customer.",
    "ARD-017.",
    "Push notifications later.",
    "13-pwa-architecture.md")

add(23, "store-customer-pwa", "Store Customer PWA Architecture", "Accepted", [6, 16, 23],
    "Customers need home-screen re-engagement.",
    "Generic app won't feel like the store.",
    "Per-store installable PWA with store branding and start_url to storefront (ARD-029).",
    "Growth loop store PWA.",
    "Single global consumer app.",
    "Many manifests.",
    "Dynamic manifest endpoint.",
    "Membership portal inside PWA.",
    "StorePwaInstalled events.",
    "Customer JWT only.",
    "ARD-029.",
    "Offline catalog stretch.",
    "storefront-pwa-architecture.md")

# fix deps for 23 - should be [6,16] not self
RAW[-1]["deps"] = [6, 16, 22]

add(24, "offline-first-staff-pos", "Offline-First Staff POS Strategy", "Accepted", [22, 9],
    "Flaky networks at counters.",
    "Silent conflict on sync dangerous.",
    "Online-first P0; offline queue P1; conflict=reject-and-review on stock shortage; idempotent sync keys.",
    "Safe degradation.",
    "Full offline-first CRDT.",
    "P1 delay acceptable.",
    "Sync API; IDB drafts.",
    "SaleCompleted on sync.",
    "Sync failure metrics.",
    "No silent double charge.",
    "ARD-017; ADR-0005.",
    "Richer conflict UI later.",
    "")

add(25, "state-management", "State Management Strategy", "Accepted", [16],
    "Need client state for POS cart and server state for lists.",
    "Putting server data only in Zustand duplicates bugs.",
    "Zustand for ephemeral UI/POS cart; TanStack Query for server state.",
    "Clear separation.",
    "Redux everywhere; Context only.",
    "Two libraries.",
    "Module pos/ui/state.",
    "N/A",
    "Invalidate queries on realtime.",
    "Clear on logout.",
    "All merchant UI ARDs.",
    "URL state for deep links.",
    "docs/tech/zustand.md; tanstack-query.md")

add(26, "data-fetching", "Data Fetching Strategy", "Accepted", [16, 25],
    "RSC + client fetch mix.",
    "Waterfalls on POS.",
    "RSC for dashboards/marketing; client Query for interactive POS/CRM; Route Handlers for JSON public/mobile.",
    "Fits Next 15.",
    "Client-only SPA.",
    "Cognitive load.",
    "Avoid RSC waterfalls on POS.",
    "N/A",
    "Track slow queries via OTel.",
    "Auth on fetches.",
    "Per-surface guidelines in tech/nextjs.",
    "Partial prerender later.",
    "")

add(27, "forms-validation", "Form and Validation Strategy", "Accepted", [16, 19],
    "Forms everywhere.",
    "Client-only validation insecure.",
    "React Hook Form + Zod; Zod also at API boundary.",
    "Type-safe UX + security.",
    "Formik; yup only.",
    "Schema duplication risk—share where practical.",
    "zodResolver.",
    "N/A",
    "N/A",
    "Never trust client alone.",
    "All form UIs.",
    "i18n errors later.",
    "docs/tech/zod.md")

add(28, "frontend-error-ux", "Frontend Error Handling UX", "Accepted", [18, 21],
    "Network/validation failures common.",
    "Silent failures destroy trust at POS.",
    "Typed error envelope toasts/inline; recovery paths for barcode miss; optimistic UI only where safe.",
    "Operability.",
    "Alert() spam.",
    "Design effort.",
    "correlationId shown to support optionally.",
    "N/A",
    "Error events sampled.",
    "No OTP in errors.",
    "UI rules.",
    "Offline banners staff PWA.",
    "")

# ---- BACKEND 029-040 ----
add(29, "backend-layering", "Backend Clean Architecture Layering", "Accepted", [2, 4, 16],
    "Next.js invites logic in routes.",
    "Unmaintainable handlers.",
    "Routes/Server Actions → application use cases → domain ← infra (Drizzle/Mongo/EMQX/MinIO/SMS).",
    "Testable & extractable.",
    "Fat controllers.",
    "More files.",
    "Module layout mandatory.",
    "Use cases define TX boundaries.",
    "Use cases emit analytics ports.",
    "AuthZ in application.",
    "All backend ARDs.",
    "N/A",
    "architecture-rules.md")

add(30, "api-standards", "API Architecture and Standards", "Accepted", [29],
    "Many clients: web staff, storefront, future mobile.",
    "Inconsistent errors/auth break clients.",
    "/api/v1 JSON; Zod validate; error envelope with correlationId; Idempotency-Key for sale/order.",
    "Stability.",
    "tRPC only; GraphQL now.",
    "Versioning overhead.",
    "Document in each ARD.",
    "N/A",
    "API metrics.",
    "Rate limits; no OTP in prod.",
    "api-rules.md.",
    "OpenAPI generate later.",
    "15-api-architecture.md")

add(31, "merchant-authentication", "Merchant Authentication Architecture", "Accepted", [29, 30],
    "Merchants need passwordless access.",
    "Email/password poor for shop owners.",
    "Phone OTP for merchant staff; JWT session; AUTH-* rules.",
    "Fits market.",
    "Passwordless magic links email.",
    "SMS cost/reliability.",
    "identity module.",
    "MerchantLoggedIn.",
    "Auth funnel.",
    "Rate limit OTP 3/min.",
    "ARD-002.",
    "WebAuthn later.",
    "09-authentication-architecture.md")

add(32, "customer-sms-otp", "Customer SMS OTP Authentication", "Accepted", [31, 7],
    "Customers need login for portal/PWA.",
    "Reusing merchant tokens is catastrophic.",
    "Separate customer OTP audience and JWT claims role=customer; distinct routes.",
    "Audience isolation.",
    "Shared token for both.",
    "Two OTP flows.",
    "ARD-030.",
    "CustomerLoggedIn.",
    "Customer auth funnel.",
    "Cannot call merchant APIs.",
    "ARD-030.",
    "Social login later.",
    "")

add(33, "nextauth-jwt", "NextAuth JWT Strategy", "Accepted", [31, 32],
    "Need session integration with Next.",
    "Server sessions conflict with AUTH-05 and scale.",
    "NextAuth JWT strategy; stateless; tokenVersion; secure cookies.",
    "Horizontal scale.",
    "Database sessions.",
    "Logout-all needs version bump.",
    "Callbacks add merchantId/roles or customer claims.",
    "N/A",
    "N/A",
    "Short TTL; HTTPS.",
    "identity infra.",
    "Refresh rotation hardening.",
    "docs/tech/nextauth.md; jwt.md")

add(34, "authorization-rbac", "Authorization RBAC Model", "Accepted", [33],
    "Multiple roles.",
    "IDOR/tenant leaks.",
    "RBAC: merchant_owner, store_employee, customer, platform_admin; every query tenant/store scoped.",
    "Least privilege.",
    "ABAC full; everyone owner.",
    "Role matrix docs needed.",
    "Checks in application services.",
    "Denied access audit.",
    "AuthZ deny metrics.",
    "Critical.",
    "Tests mandatory each resource.",
    "Attribute policies later.",
    "06-security-architecture.md")

add(35, "outbox-workers", "Background Jobs and Transactional Outbox", "Accepted", [29, 36],
    "Side effects after commit must be reliable.",
    "Publish-after-commit can lose events.",
    "Transactional outbox in PostgreSQL; worker publishes to EMQX, Mongo warehouse, audit, cache invalidation.",
    "At-least-once reliability.",
    "Dual write without outbox.",
    "Worker ops.",
    "outbox_events table; polls.",
    "All domain events.",
    "Lag metrics.",
    "No PII in worker logs.",
    "ARD-001/015/024.",
    "Partition outbox later.",
    "04-event-driven-architecture.md")

add(36, "event-driven-architecture", "Event-Driven Architecture", "Accepted", [2, 29],
    "Decouple realtime, analytics, cache.",
    "Sync coupling brittle.",
    "Domain events + envelope + outbox; at-least-once; idempotent consumers.",
    "Extraction-ready.",
    "Full event sourcing MVP.",
    "Eventual consistency complexity.",
    "event-catalog.md governance.",
    "All BC publish past-tense events.",
    "Warehouse mirror.",
    "Scrub payloads in logs.",
    "Every mutating ARD.",
    "Schema registry later.",
    "event-catalog.md")

add(37, "event-catalog-governance", "Event Naming and Schema Governance", "Accepted", [36],
    "Many producers/consumers.",
    "Payload drift breaks consumers.",
    "Past-tense names; versioned payloads; catalog + store-first addendum authoritative; changes require doc update in same PR/ARD.",
    "Contract clarity.",
    "Ad-hoc event names.",
    "Process overhead.",
    "payloadVersion field.",
    "Ubiquitous language.",
    "Warehouse mapping.",
    "Minimize PII.",
    "CI docstring check optional later.",
    "Compatibility windows.",
    "event-catalog-store-first-addendum.md")

add(38, "emqx-realtime", "EMQX Event Bus / Realtime Architecture", "Accepted", [36],
    "Merchants need live orders/sales/inventory.",
    "Polling-only too slow/noisy.",
    "EMQX MQTT topics per merchant; QoS1; ACL by tenant; never block checkout on publish.",
    "Fits realtime reqs.",
    "Pusher; SSE only; Redis pubsub only.",
    "Broker ops.",
    "Topics in 17-message-broker.",
    "Order/Sale fan-out.",
    "Disconnect metrics.",
    "Short-lived client creds.",
    "ARD-015.",
    "Cluster HA prod.",
    "08-real-time-architecture.md")

add(39, "mqtt-client-strategy", "Realtime Client Strategy MQTT with Poll Fallback", "Accepted", [38, 25],
    "Browsers must receive updates.",
    "WebSocket custom stack duplicates EMQX features.",
    "MQTT over WebSocket to EMQX; invalidate TanStack Query; poll fallback on disconnect.",
    "Resilience.",
    "Native WS protocol from app servers.",
    "Client complexity.",
    "Token mint API.",
    "N/A",
    "Client reconnect metrics.",
    "Topic ACL.",
    "Merchant UI boards; ARD-015.",
    "Push mobile later.",
    "")

add(40, "minio-storage", "File Storage MinIO Strategy", "Accepted", [29],
    "Receipts, product images, logos, QR assets.",
    "DB BLOBs hurt backups.",
    "MinIO S3 API; presigned upload/download; keys in PG.",
    "Local S3 parity.",
    "Cloud S3 only; filesystem disk.",
    "Another service.",
    "Buckets receipts/products/merchantdocs.",
    "ReceiptRef VO.",
    "N/A",
    "Private buckets; type/size limits.",
    "ARD-007, 004, 033.",
    "CDN in front.",
    "docs/tech/minio.md")

# ---- DATABASE 041-050 ----
add(41, "postgresql-architecture", "PostgreSQL Architecture", "Accepted", [4, 29],
    "Need relational SoT.",
    "Document DB as SoT weak for money/stock.",
    "PostgreSQL latest stable sole OLTP SoT; UUID PKs; soft deletes; timestamps.",
    "Integrity + SQL power.",
    "MySQL; Cockroach only.",
    "Ops familiarity assumed.",
    "Conn pooling per instance.",
    "All aggregates.",
    "Not clickstream.",
    "Least privilege roles.",
    "Compose + managed prod.",
    "Partitioning at scale.",
    "database-architecture.md")

add(42, "drizzle-orm", "Drizzle ORM Exclusive Strategy", "Accepted", [41],
    "Need typed SQL-first access.",
    "Prisma previously considered; weak for explicit SQL/index control desired.",
    "Drizzle ORM only SQL ORM; Kit migrations; repos in infra; domain never imports Drizzle. Forbidden: Prisma/TypeORM/Sequelize/MikroORM/Objection.",
    "SQL transparency + DDD fit.",
    "Prisma; raw pg only.",
    "Less battery-included migrate UX than some ORMs.",
    "schema/migrations under infrastructure/database.",
    "Mapping adapters.",
    "N/A",
    "Parameterized only.",
    "All PG ARDs; supersedes docs/decisions ADR-0007 numbering.",
    "Stay current major.",
    "docs/tech/drizzle-orm.md")

add(43, "database-modeling", "Database Modeling Standards", "Accepted", [42],
    "Scale to 50k merchants.",
    "CRUD tables without growth thinking fail.",
    "Query-first modeling; estimate rows; FKs; checks; partial uniques with soft delete; version optimistic locks where concurrent.",
    "Tier-0 DB quality.",
    "Generate schema from UI forms.",
    "More design time.",
    "data-modeling-guidelines.md mandatory in ARDs.",
    "Aggregates map to tables.",
    "N/A",
    "Tenant columns.",
    "Every PG ARD Database Design section.",
    "Partitioning ADR when thresholds hit.",
    "data-modeling-guidelines.md")

add(44, "indexing-standards", "Indexing Standards", "Accepted", [43],
    "POS barcode/phone must be fast.",
    "ORM default indexes insufficient.",
    "Explicit indexes; merchant_id leftmost composites; partial unique for soft delete; covering where justified; document why per index.",
    "Meets NFR search/barcode.",
    "Index everything.",
    "Write amplification if over-indexed.",
    "indexing-strategy.md.",
    "Hot paths POS/CRM/orders.",
    "N/A",
    "N/A",
    "EXPLAIN on hot paths staging.",
    "Tune quarterly.",
    "indexing-strategy.md")

add(45, "query-design", "Query Design Standards", "Accepted", [44],
    "Avoid N+1 and deep OFFSET.",
    "Dashboard scans kill DB.",
    "Keyset pagination; select projections; no unbounded aggregates on request—use projections; always tenant filter.",
    "Performance budgets.",
    "OFFSET everywhere; ORM default includes.",
    "More query craft.",
    "query-strategy.md.",
    "CompleteSale single TX.",
    "Prefer Redis before DB for hot entities.",
    "AuthZ in queries.",
    "All list endpoints.",
    "Read replicas later.",
    "query-strategy.md")

add(46, "drizzle-migrations", "Migration Strategy Drizzle Kit", "Accepted", [42],
    "Schema evolve safely.",
    "Manual SQL drift.",
    "Drizzle Kit versioned SQL; forward-only prod; expand/contract; migrate job before traffic.",
    "Reviewable DDL.",
    "Auto migrate on boot prod.",
    "Slower releases.",
    "migrations/ folder.",
    "N/A",
    "N/A",
    "Lock awareness.",
    "CI apply staging.",
    "Online index builds when large.",
    "")

add(47, "data-integrity", "Data Integrity Soft Delete and Audit Fields", "Accepted", [43],
    "Compliance and undo.",
    "Hard deletes lose history.",
    "Soft delete deleted_at; created_at/updated_at mandatory; audit_logs/Mongo audit for sensitive; optimistic version where needed.",
    "NFR-10.",
    "Hard delete always.",
    "Table bloat—purge jobs later.",
    "Partial uniques.",
    "Supports CRM restore stories.",
    "N/A",
    "Audit evidence.",
    "All tables.",
    "Purge policies ADR retention.",
    "")

add(48, "multi-tenant-isolation", "Multi-Tenant Data Isolation", "Accepted", [41, 34],
    "Shared DB SaaS.",
    "Cross-tenant leaks fatal.",
    "Shared schema row-level merchant_id; store_id where needed; repo filters from auth context; tests mandatory.",
    "Cost-effective isolation.",
    "DB-per-tenant MVP.",
    "Noisy neighbor risk mitigated by indexes/pooling.",
    "Every tenant table.",
    "Membership store scope.",
    "Analytics tenant filters.",
    "Critical controls.",
    "05-multi-tenant-strategy.md.",
    "Schema-per-tenant unlikely.",
    "")

add(49, "inventory-synchronization", "Inventory Synchronization Strategy", "Accepted", [8, 9, 11],
    "POS and pickup both change stock.",
    "Oversell damages trust.",
    "Stock decrement in CompleteSale TX; for pickup decrement/reserve on paid or preparing (document in impl); optimistic version on stock_items; Inventory* events invalidate caches/realtime.",
    "Consistent enough for MVP retail.",
    "Eventual stock only.",
    "Race under extreme contention—version helps.",
    "stock_items.version.",
    "InventoryChanged.",
    "Out-of-stock tracking.",
    "Audit adjustments.",
    "ARD-006,007,034.",
    "Reservations table if needed.",
    "")

add(50, "search-barcode", "Search and Barcode Scanning Strategy", "Accepted", [8, 16],
    "POS needs ≤1s barcode and ≤100ms search feel.",
    "Full table search fails.",
    "B-tree unique (merchant_id,barcode); cache-aside barcode keys; fuzzy via pg_trgm and/or client catalog cache; camera BarcodeDetector with fallback lib.",
    "Meets NFR.",
    "Elasticsearch MVP.",
    "ES ops deferred.",
    "Redis barcode keys TTL 300s.",
    "N/A",
    "Scan success/fail analytics.",
    "N/A",
    "ARD-005,007.",
    "Typesense later ADR.",
    "")

print("defined", len(RAW), "so far")
