/**
 * ADR-097 merchant catalog / inventory Persian copy.
 */

export const CATALOG_UI_COPY_FA = {
  productsTitle: "کالاها",
  productsSubtitle: "مدیریت کالا، بارکد و قیمت به تومان",
  inventoryTitle: "موجودی",
  inventorySubtitle: "تعدیل موجودی قفسه برای فروشگاه فعال",
  searchPlaceholder: "جستجوی نام کالا…",
  addProduct: "افزودن کالا",
  editProduct: "ویرایش کالا",
  saveProduct: "ذخیره کالا",
  softDelete: "حذف از فهرست",
  softDeleteConfirm: "این کالا از فهرست فعال‌ها حذف می‌شود (تاریخچه فروش حفظ می‌شود).",
  nameLabel: "نام کالا",
  skuLabel: "کد کالا (SKU)",
  barcodeLabel: "بارکد",
  priceTomanLabel: "قیمت (تومان)",
  descriptionLabel: "توضیحات",
  categoryLabel: "دسته‌بندی",
  categoryNone: "بدون دسته",
  categoriesTitle: "دسته‌بندی‌ها",
  addCategory: "افزودن دسته",
  categoryNameLabel: "نام دسته",
  saveCategory: "ذخیره دسته",
  deleteCategory: "حذف دسته",
  storeLabel: "فروشگاه",
  quantityLabel: "موجودی فعلی",
  adjustDeltaLabel: "تغییر موجودی (±)",
  adjustReasonLabel: "دلیل (اختیاری)",
  adjustSubmit: "ثبت تعدیل",
  initialStockLabel: "موجودی اولیه",
  loadingProducts: "در حال بارگذاری کالاها…",
  loadingInventory: "در حال بارگذاری موجودی…",
  saving: "در حال ذخیره…",
  emptyProducts: "هنوز کالایی ثبت نشده — اولین کالا را اضافه کنید",
  emptyInventory: "برای این فروشگاه موجودی ثبت نشده است.",
  saveSuccess: "کالا ذخیره شد",
  deleteSuccess: "کالا از فهرست حذف شد",
  adjustSuccess: "موجودی به‌روز شد",
  categorySuccess: "دسته‌بندی ذخیره شد",
  networkError: "ارتباط برقرار نشد. دوباره تلاش کنید.",
  priceHint: "مبلغ را به تومان وارد کنید",
  backToList: "بازگشت به فهرست",
  backToDashboard: "داشبورد",
  openInventory: "موجودی",
  openProducts: "کالاها",
  openPos: "صندوق فروش",
  noStore: "فروشگاهی برای این حساب تعریف نشده است.",
  updatedAt: "آخرین به‌روزرسانی",
  imageTitle: "تصویر کالا",
  imageHint: "PNG، JPEG، WebP یا GIF — حداکثر ۵ مگابایت",
  imageUpload: "بارگذاری تصویر",
  imageUploading: "در حال بارگذاری تصویر…",
  imageDelete: "حذف تصویر",
  imagePresent: "تصویر ثبت شده است",
  imageAbsent: "هنوز تصویری بارگذاری نشده",
  imageSaveFirst: "ابتدا کالا را ذخیره کنید، سپس تصویر را بارگذاری کنید.",
  imageSuccess: "تصویر کالا ذخیره شد",
  imageDeleted: "تصویر کالا حذف شد",
  movementsTitle: "تاریخچه موجودی",
  movementsOpen: "تاریخچه حرکت",
  movementsEmpty: "هنوز حرکتی برای این کالا ثبت نشده است.",
  movementsLoading: "در حال بارگذاری تاریخچه…",
  movementsDelta: "تغییر",
  movementsLoadMore: "موارد بیشتر",
  lowStockLabel: "کم‌موجودی",
} as const;
