/**
 * ADR-101 — Persian pickup order board copy (uiuxpromax brief).
 */

import { ORDER_STATUS_LABELS_FA } from "../../../ordering-domain/index.js";

export const ORDERS_UI_COPY_FA = {
  brand: "کاسبینو",
  boardTitle: "تابلوی سفارش‌های پیکاپ",
  boardSubtitle: "تحویل حضوری — آماده‌سازی و تحویل به مشتری",
  backToDashboard: "داشبورد",
  openPos: "صندوق فروش",
  openCustomers: "مشتریان",
  storeLabel: "فروشگاه",
  storePlaceholder: "فروشگاه را انتخاب کنید",
  filterLabel: "وضعیت سفارش",
  filterAllOpen: "باز",
  filterAll: "همه",
  loading: "در حال بارگذاری سفارش‌ها…",
  empty: "سفارش بازی نیست — سفارش‌های ویترین اینجا می‌آیند",
  emptyFilter: "در این وضعیت سفارشی نیست",
  networkError: "ارتباط برقرار نشد. دوباره تلاش کنید.",
  actionErrorFallback: "انجام عملیات ممکن نشد.",
  actionSuccess: "وضعیت سفارش به‌روز شد",
  pollHint: "به‌روزرسانی خودکار هر ۱۵ ثانیه",
  lastPolled: "آخرین به‌روزرسانی",
  refreshNow: "تازه‌سازی",
  realtimeConnected: "اتصال لحظه‌ای برقرار است",
  realtimePolling: "به‌روزرسانی دوره‌ای فعال است",
  realtimeReconnecting: "در حال اتصال مجدد…",
  linesLabel: "اقلام",
  totalLabel: "مبلغ",
  createdLabel: "ثبت",
  statusLabel: "وضعیت",
  fulfillmentHint: "فقط دریافت حضوری از فروشگاه",
  readyHoldOk: "مهلت آماده تحویل: تا ۲۴ ساعت پس از آماده‌ شدن",
  readyHoldUrgent: "مهلت آماده تحویل رو به پایان است",
  readyHoldExpired: "مهلت ۲۴ ساعته گذشته — در صورت اجرای زمان‌بند، لغو می‌شود",
  unpaidHint: "در انتظار پرداخت — اگر پرداخت نشود لغو می‌شود",
  cancelReasonLabel: "دلیل لغو",
  actionPreparing: "شروع آماده‌سازی",
  actionReady: "آماده تحویل",
  actionPickedUp: "تحویل گرفت",
  actionComplete: "تکمیل سفارش",
  actionCancel: "لغو سفارش",
  actionRefund: "بازپرداخت دستی",
  cancelConfirm: "لغو این سفارش قطعی است؟",
  refundConfirm: "بازپرداخت دستی ثبت شود؟ (خودکار نیست)",
  acting: "در حال اعمال…",
  noDate: "—",
  currencyHint: "مبالغ به تومان · تاریخ شمسی (تهران)",
  statusPaid: ORDER_STATUS_LABELS_FA.paid,
  statusPreparing: ORDER_STATUS_LABELS_FA.preparing,
  statusReady: ORDER_STATUS_LABELS_FA.ready_for_pickup,
  statusPickedUp: ORDER_STATUS_LABELS_FA.picked_up,
  statusCompleted: ORDER_STATUS_LABELS_FA.completed,
  statusPending: ORDER_STATUS_LABELS_FA.pending_payment,
  statusCancelled: ORDER_STATUS_LABELS_FA.cancelled,
  statusRefunded: ORDER_STATUS_LABELS_FA.refunded,
} as const;

export type OrdersUiCopyKey = keyof typeof ORDERS_UI_COPY_FA;
