/**
 * ADR-098 — Persian CRM merchant copy (uiuxpromax brief).
 */

export const CRM_UI_COPY_FA = {
  brand: "کاسبینو",
  customersTitle: "مشتریان",
  customersSubtitle: "اعضای مغازه — شماره موبایل ایرانی",
  profileTitle: "پروفایل مشتری",
  backToDashboard: "داشبورد",
  backToCustomers: "بازگشت به مشتریان",
  openPos: "صندوق فروش",
  openProducts: "کالاها",
  storeLabel: "فروشگاه",
  storePlaceholder: "فروشگاه را انتخاب کنید",
  searchPhonePlaceholder: "جستجو با شماره (۰۹…)",
  loadingCustomers: "در حال بارگذاری مشتریان…",
  loadingProfile: "در حال بارگذاری پروفایل…",
  loadingHistory: "در حال بارگذاری تاریخچه…",
  emptyCustomers: "هنوز مشتری‌ای ثبت نشده — از صندوق شماره بگیرید",
  emptySegment: "در این بخش مشتری‌ای نیست",
  emptyHistory: "هنوز خریدی ثبت نشده",
  networkError: "ارتباط برقرار نشد. دوباره تلاش کنید.",
  segmentAll: "همه",
  segmentNew: "جدید",
  segmentReturning: "بازگشتی",
  segmentLapsed: "بازمانده",
  phoneLabel: "شماره موبایل",
  sourceLabel: "منبع عضویت",
  joinedLabel: "تاریخ عضویت",
  statusLabel: "وضعیت",
  segmentLabel: "بخش",
  purchaseCountLabel: "تعداد خرید",
  totalSpendLabel: "جمع خرید",
  firstPurchaseLabel: "اولین خرید",
  lastPurchaseLabel: "آخرین خرید",
  historyTitle: "تاریخچه خرید",
  softDelete: "حذف از فهرست",
  deleting: "در حال حذف…",
  deleteSuccess: "مشتری از فهرست حذف شد",
  sourcePos: "صندوق",
  sourceQr: "کیوآر",
  sourceStorefront: "ویترین",
  sourcePickup: "پیکاپ",
  statusActive: "فعال",
  statusInactive: "غیرفعال",
  statusSuspended: "تعلیق",
  dashboardCustomersTitle: "مشتریان",
  dashboardCustomersHint: "عضویت‌های فعال و بخش‌ها",
  dashboardOpenCrm: "مشاهده مشتریان",
  dashboardLoading: "در حال بارگذاری آمار مشتریان…",
  dashboardEmptyStore: "فروشگاهی برای نمایش نیست",
  walletTitle: "کیف امتیاز",
  walletBalance: "موجودی",
  walletPointsUnit: "امتیاز",
  walletLastEarn: "آخرین کسب",
  walletEmpty: "هنوز کیف امتیازی ندارد",
  walletLoading: "در حال بارگذاری کیف امتیاز…",
  noDate: "—",
} as const;

export type CrmUiCopyKey = keyof typeof CRM_UI_COPY_FA;
