/**
 * ADR-099 — Persian loyalty merchant/customer copy (uiuxpromax brief).
 */

export const LOYALTY_UI_COPY_FA = {
  brand: "کاسبینو",
  settingsTitle: "باشگاه مشتریان",
  settingsSubtitle: "قانون امتیاز هر فروشگاه · مبالغ به تومان",
  storeLabel: "فروشگاه",
  storePlaceholder: "فروشگاه را انتخاب کنید",
  amountTomanLabel: "تومان لازم برای هر امتیاز",
  amountHint: "پیش‌فرض: هر ۱۰٬۰۰۰ تومان = ۱ امتیاز (معادل ۱۰۰٬۰۰۰ ریال)",
  pointsPerUnitLabel: "امتیاز به‌ازای هر واحد",
  expiryMonthsLabel: "ماه تا انقضا بعد از آخرین کسب",
  expiryDisabledLabel: "انقضای امتیاز غیرفعال باشد",
  save: "ذخیره قانون",
  saving: "در حال ذخیره…",
  loadRule: "در حال بارگذاری قانون…",
  saved: "قانون امتیاز ذخیره شد",
  defaultRuleHint: "هنوز قانونی ذخیره نشده — با ذخیره، پیش‌فرض فعال می‌شود",
  networkError: "ارتباط برقرار نشد. دوباره تلاش کنید.",
  backToDashboard: "داشبورد",
  openPos: "صندوق فروش",
  openCustomers: "مشتریان",
  walletTitle: "کیف امتیاز",
  walletBalance: "موجودی",
  pointsUnit: "امتیاز",
  lastEarnLabel: "آخرین کسب امتیاز",
  noWallet: "هنوز کیف امتیازی ندارد",
  noDate: "—",
  loadingWallet: "در حال بارگذاری کیف امتیاز…",
  customerWalletTitle: "کیف امتیاز",
  customerWalletSubtitle: "فقط امتیاز همین فروشگاه",
  customerEmpty: "هنوز امتیازی ندارید",
  customerLoginHint: "برای مشاهدهٔ کیف امتیاز وارد شوید",
  customerLoading: "در حال بارگذاری کیف امتیاز…",
  customerLedgerTitle: "تاریخچه امتیاز",
  entryEarn: "کسب",
  entryRedeem: "مصرف",
  entryExpire: "انقضا",
  posRedeemTitle: "اعمال امتیاز",
  posRedeemPointsLabel: "تعداد امتیاز",
  posRedeemApply: "کسر امتیاز",
  posRedeeming: "در حال کسر…",
  posRedeemSuccess: "امتیاز با موفقیت کسر شد",
  posBalanceLabel: "موجودی امتیاز",
  posLookupWallet: "مشاهده موجودی",
  posNoMembership: "عضویت برای این شماره یافت نشد",
  tomanSuffix: "تومان",
} as const;

export type LoyaltyUiCopyKey = keyof typeof LOYALTY_UI_COPY_FA;
